---@mod codetyper.prompts Minimal prompt adapter
---
--- Prompt construction has been migrated to the Python agent.
---
--- The original Lua prompt templates are intentionally gutted to
--- avoid duplicating logic. Consumers should forward raw context to
--- the agent which owns prompt construction and LLM interactions.
---
--- This module provides lightweight stubs for compatibility: it
--- returns a short placeholder string for all prompts so existing
--- consumers won't error during the migration.

local M = {}
local PLACEHOLDER = "[PROMPTS_MOVED_TO_AGENT] Prompts are now hosted by the Python agent. Send raw context to the agent."

-- Minimal prompt categories (provide placeholders for backward compatibility)
M.system = setmetatable({}, { __index = function() return PLACEHOLDER end })
M.code = setmetatable({}, { __index = function() return PLACEHOLDER end })
M.ask = setmetatable({}, { __index = function() return PLACEHOLDER end })
M.refactor = setmetatable({}, { __index = function() return PLACEHOLDER end })
M.document = setmetatable({}, { __index = function() return PLACEHOLDER end })
M.agent = setmetatable({}, { __index = function() return PLACEHOLDER end })

--- Get a prompt (compat shim)
---@param category string
---@param name string
---@param vars? table
---@return string
function M.get(category, name, vars)
  -- Return a stable placeholder string. Full prompts are generated by the agent.
  return PLACEHOLDER
end

--- List available prompts (empty during migration)
---@return table
function M.list()
  return {}
end

return M
