local params = require("codetyper.params.agents.scheduler")

local state = {
  buf = nil,
  win = nil,
  original_event = nil,
  callback = nil,
  llm_response = nil,
  attached_files = nil,
  entries = {},
  current_index = 1,
  list_buf = nil,
  list_win = nil,
  diff_buf = nil,
  diff_win = nil,
  is_open = false,
  listeners = {},
  total_prompt_tokens = 0,
  total_response_tokens = 0,
  current_provider = nil,
  current_model = nil,
  queue_buf = nil,
  queue_win = nil,
  listener_id = nil,
  queue_listener_id = nil,
  win_id = nil,
  buf_id = nil,
  throbber = nil,
  timer = nil,
  stage_text = "Thinking...",
  current_suggestion = nil,
  suggestions = {},
  extmark_id = nil,
  bufnr = nil,
  line = nil,
  col = nil,
  using_copilot = false,
  usage = {},
  all_usage = {},
  session_start = os.time(),
  loaded = false,
  running = false,
  poll_interval = 100, -- ms
  paused = false,
  config = params.config,
}

return state
