local lang_map = {
	-- JavaScript/TypeScript
	ts = "TypeScript",
	tsx = "TypeScript React (TSX)",
	js = "JavaScript",
	jsx = "JavaScript React (JSX)",
	mjs = "JavaScript (ESM)",
	cjs = "JavaScript (CommonJS)",
	-- Python
	py = "Python",
	pyw = "Python",
	pyx = "Cython",
	-- Systems languages
	c = "C",
	h = "C Header",
	cpp = "C++",
	hpp = "C++ Header",
	cc = "C++",
	cxx = "C++",
	rs = "Rust",
	go = "Go",
	-- JVM languages
	java = "Java",
	kt = "Kotlin",
	kts = "Kotlin Script",
	scala = "Scala",
	clj = "Clojure",
	-- Web
	html = "HTML",
	css = "CSS",
	scss = "SCSS",
	sass = "Sass",
	less = "Less",
	vue = "Vue",
	svelte = "Svelte",
	-- Scripting
	lua = "Lua",
	rb = "Ruby",
	php = "PHP",
	pl = "Perl",
	sh = "Shell (Bash)",
	bash = "Bash",
	zsh = "Zsh",
	fish = "Fish",
	ps1 = "PowerShell",
	-- .NET
	cs = "C#",
	fs = "F#",
	vb = "Visual Basic",
	-- Data/Config
	json = "JSON",
	yaml = "YAML",
	yml = "YAML",
	toml = "TOML",
	xml = "XML",
	sql = "SQL",
	graphql = "GraphQL",
	-- Other
	swift = "Swift",
	dart = "Dart",
	ex = "Elixir",
	exs = "Elixir Script",
	erl = "Erlang",
	hs = "Haskell",
	ml = "OCaml",
	r = "R",
	jl = "Julia",
	nim = "Nim",
	zig = "Zig",
	v = "V",
	md = "Markdown",
	mdx = "MDX",
}

return lang_map
